version: "3.9"

services:
  pgrechner_app_test:
    build: .
    container_name: pgrechner_app_test
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - pgrechner_db_test
    networks:
      - proxy_network
    ports:
      - "5001:5001"


  pgrechner_db_test:
    image: postgres:15-alpine
    container_name: pgrechner_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgrechner
    volumes:
      - pgrechner_db_data:/var/lib/postgresql/data
    networks:
      - proxy_network

  pgrechner_nginx:
    image: nginx:alpine
    container_name: pgrechner_nginx_test
    environment:
      - VIRTUAL_HOST=opbrechner.optimum-pflegeberatung.de
      - LETSENCRYPT_HOST=opbrechner.optimum-pflegeberatung.de
      - LETSENCRYPT_EMAIL=alex.torrescanety@optimum-pflegeberatung.de
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pgrechner_app_test
    networks:
      - proxy_network

volumes:
  pgrechner_db_data:
    

networks:
  proxy_network:
    # external: true # remove comment when in Production
    