version: '3.8'

services:
  app:
    build: .
    container_name: pgrechner_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pgrechner
      - SECRET_KEY=change-me

  db:
    image: postgres:15-alpine
    container_name: pgrechner_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgrechner
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: pgrechner_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db-data: