version: "3.9"

services:
  pgrechner_app:
    build: .
    container_name: pgrechner_app
    env_file: .env
    depends_on:
      - pgrechner_db
    networks:
      - proxy_network

  pgrechner_db:
    image: postgres:15-alpine
    container_name: pgrechner_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgrechner
    volumes:
      - pgrechner_db_data:/var/lib/postgresql/data
    networks:
      - proxy_network

  pgrechner_nginx:
    image: nginx:alpine
    container_name: pgrechner_nginx
    environment:
      - VIRTUAL_HOST=opbrechner.optimum-pflegeberatung.de
      - LETSENCRYPT_HOST=opbrechner.optimum-pflegeberatung.de
      - LETSENCRYPT_EMAIL=alex.torrescanety@optimum-pflegeberatung.de
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pgrechner_app
    networks:
      - proxy_network

volumes:
  pgrechner_db_data:

networks:
  proxy_network:
    external: true
    